//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec Test

module LiveDecayingCircleLenses =
    open Launcher.MovingBall

    let id =
        (fun (x: LiveDecayingCircle) -> x.id), (fun (x: LiveDecayingCircle) (value: System.Guid) -> { x with id = value })

    let tStart =
        (fun (x: LiveDecayingCircle) -> x.tStart),
        (fun (x: LiveDecayingCircle) (value: uint) -> { x with tStart = value })

    let circle =
        (fun (x: LiveDecayingCircle) -> x.circle),
        (fun (x: LiveDecayingCircle) (value: DecayingCircle) -> { x with circle = value })
namespace rec Test


namespace rec Test

